// ============================================================================
//  Politicas GENERALES (oficiales) por red social: normas comunitarias,
//  condiciones, privacidad, propiedad intelectual. Extraidas de los paneles web.
// ============================================================================
window.POLITICAS_GENERALES = {
  "Facebook": [{ t: "Normas Comunitarias", u: "https://transparency.meta.com/es-la/policies/community-standards/" }, { t: "Condiciones del servicio", u: "https://www.facebook.com/legal/terms" }, { t: "Política de privacidad", u: "https://www.facebook.com/privacy/policy/" }, { t: "Propiedad intelectual (derechos de autor y marcas)", u: "https://www.facebook.com/help/1020633957973118" }],
  "Instagram": [{ t: "Normas comunitarias", u: "https://help.instagram.com/477434105621119" }, { t: "Condiciones de uso", u: "https://help.instagram.com/581066165581870" }, { t: "Política de privacidad", u: "https://privacycenter.instagram.com/policy" }, { t: "Propiedad intelectual", u: "https://help.instagram.com/535503073130320" }],
  "LinkedIn": [{ t: "Políticas de la Comunidad Profesional", u: "https://www.linkedin.com/legal/professional-community-policies" }, { t: "Acuerdo de usuario", u: "https://www.linkedin.com/legal/user-agreement" }, { t: "Política de privacidad", u: "https://www.linkedin.com/legal/privacy-policy" }, { t: "Política de derechos de autor", u: "https://www.linkedin.com/legal/copyright-policy" }],
  "TikTok": [{ t: "Normas de la comunidad", u: "https://www.tiktok.com/community-guidelines/es" }, { t: "Términos de servicio", u: "https://www.tiktok.com/legal/page/row/terms-of-service/es" }, { t: "Política de privacidad", u: "https://www.tiktok.com/legal/page/row/privacy-policy/es" }, { t: "Política de propiedad intelectual", u: "https://www.tiktok.com/legal/page/global/copyright-policy/es" }],
  "WhatsApp": [{ t: "Condiciones del servicio", u: "https://www.whatsapp.com/legal/terms-of-service" }, { t: "Política de privacidad", u: "https://www.whatsapp.com/legal/privacy-policy" }, { t: "Política comercial", u: "https://www.whatsapp.com/legal/commerce-policy" }, { t: "Información legal (todas las políticas)", u: "https://www.whatsapp.com/legal" }],
  "X": [{ t: "Reglas de X", u: "https://help.x.com/es/rules-and-policies/x-rules" }, { t: "Condiciones del servicio", u: "https://x.com/es/tos" }, { t: "Política de privacidad", u: "https://x.com/es/privacy" }, { t: "Política de conducta abusiva", u: "https://help.x.com/es/rules-and-policies/abusive-behavior" }, { t: "Política de suplantación de identidad", u: "https://help.x.com/es/rules-and-policies/x-impersonation-policy" }, { t: "Política de información privada", u: "https://help.x.com/es/rules-and-policies/personal-information" }, { t: "Política de falsificaciones", u: "https://help.x.com/es/rules-and-policies/counterfeit-goods-policy" }],
  "Telegram": [{ t: "Condiciones del servicio", u: "https://telegram.org/tos" }, { t: "Política de privacidad", u: "https://telegram.org/privacy" }, { t: "Cómo reportar contenido / FAQ", u: "https://telegram.org/faq#q-there-39s-illegal-content-on-telegram-how-do-i-take-it-down" }],
  "YouTube": [{ t: "Normas de la comunidad", u: "https://www.youtube.com/howyoutubeworks/policies/community-guidelines/" }, { t: "Condiciones del servicio", u: "https://www.youtube.com/static?template=terms&hl=es" }, { t: "Política de privacidad", u: "https://policies.google.com/privacy?hl=es" }, { t: "Marcas registradas", u: "https://support.google.com/youtube/answer/6154218" }, { t: "Derechos de autor", u: "https://support.google.com/youtube/answer/2807622" }],
  "Outlook / Hotmail": [{ t: "Contrato de Servicios de Microsoft", u: "https://www.microsoft.com/servicesagreement" }, { t: "Reportar abuso / phishing", u: "https://www.microsoft.com/concern/abuse" }, { t: "Código de Conducta de Microsoft", u: "https://www.microsoft.com/servicesagreement#3a_CodeOfConduct" }],
  "Scribd": [{ t: "Términos de uso", u: "https://support.scribd.com/hc/en-us/articles/210129366-General-Terms-of-Use" }, { t: "Copyright / DMCA", u: "https://support.scribd.com/hc/en-us/sections/202602246-Copyright" }, { t: "Política de privacidad", u: "https://www.scribd.com/privacy" }]
};
